### ISSUE TITLE
Add endpoints for emojis

### ISSUE THREAD

**Issue by ZechCodes** [ZechCodes/dippy.core#30]
[Docs](https://discord.com/developers/docs/resources/emoji#list-guild-emojis)

**Instructions**
- This will need to be done in `dippy/core/api/endpoints/emojis.py`
- Fields in the docs that have a type with a question mark should be optional (ex. `?integer` should be `Optional[int]`)

**Tasks**
- [ ] List Guild Emojis
- [ ] Get Guild Emoji
- [ ] Create Guild Emoji (may require extra input from @ZechCodes )
- [ ] Modify Guild Emoji
- [ ] Delete Guild Emoji

*Be sure to commit each new endpoint separately*
