### ISSUE TITLE
Add endpoints for guilds

### ISSUE THREAD

**Issue by ZechCodes** [ZechCodes/dippy.core#31]
[Docs](https://discord.com/developers/docs/resources/guild#create-guild)

**Instructions**
- This will need to be done in `dippy/core/api/endpoints/guilds.py`
- Fields in the docs that have a type with a question mark should be optional (ex. `?integer` should be `Optional[int]`)

**Tasks**
- [ ] Create guild (may require extra input from @ZechCodes )
- [x] Get guild
- [ ] Get guild preview
- [ ] Modify guild (may require extra input from @ZechCodes )
- [ ] Delete guild
- [ ] Get guild channels
- [ ] Create guild channel (may require extra input from @ZechCodes )
- [ ] Modify guild channel positions
- [ ] List active threads
- [x] Get guild member
- [ ] List guild members
- [ ] Search guild members
- [ ] Add guild member
- [ ] Modify guild member
- [ ] Modify current member
- [ ] Modify current user nick
- [ ] Add guild member role
- [ ] Remove guild member role
- [ ] Remove guild member
- [ ] Get guild bans
- [ ] Get guild ban
- [ ] Create guild ban
- [ ] Remove guild ban
- [ ] Get guild roles
- [ ] Create guild role (may require extra input from @ZechCodes )
- [ ] Modify guild role positions
- [ ] Modify guild role (may require extra input from @ZechCodes )
- [ ] Delete guild role
- [ ] Get guild prune count
- [ ] Begin guild prune
- [ ] Get guild voice regions
- [ ] Get guild invites
- [ ] Get guild integrations
- [ ] Delete guild integration
- [ ] Get guild widget settings
- [ ] Modify guild widget
- [ ] Get guild widget
- [ ] Get guild vanity URL
- [ ] Get guild widget image
- [ ] Get guild welcome screen
- [ ] Modify guild welcome screen
- [ ] Modify current user voice state
- [ ] Modify user voice state

*Be sure to commit each new endpoint separately*
