### ISSUE TITLE
Add endpoints for guild events

### ISSUE THREAD

**Issue by ZechCodes** [ZechCodes/dippy.core#32]
[Docs](https://discord.com/developers/docs/resources/guild-scheduled-event#list-scheduled-events-for-guild)

**Instructions**
- This will need to be done in `dippy/core/api/endpoints/guild_events.py`
- Fields in the docs that have a type with a question mark should be optional (ex. `?integer` should be `Optional[int]`)

**Tasks**
- [ ] List scheduled events for guild
- [ ] Create guild scheduled event
- [ ] Get guild scheduled event
- [ ] Modify guild scheduled event
- [ ] Delete guild scheduled event
- [ ] Get guild scheduled event users

*Be sure to commit each new endpoint separately*

**Comment by eggveloper** [comment]
hi! i'd like to be assigned to this issue

also noticed a thing, in [list scheduled events for guild](https://discord.com/developers/docs/resources/guild-scheduled-event#list-scheduled-events-for-guild) there is nothing said about `with_user_count` being required and/or default.. what should i put in `QueryArgField()`?
